### ISSUE TITLE
possible to reset during long running process of multiple jobs?

### ISSUE THREAD

**Issue by vesper8** [bvanhoekelen/performance#11]
I'm deploying multiple jobs using $this->call('my:command', []); and I'm using the 'sync' queue

Each job has performance points with a ->results() at the end of it

I've noticed that all subsequent ->results() include the points and totals from all previous jobs

I would have preferred if each job was calculated separately. Is there a way to ->reset() this tool or set it to null somehow so it restarts from scratch during a long running process ?

I thought ->results() would do this by default but it looks like it doesn't

Thanks!

**Comment by bvanhoekelen** [comment]
Hey,

The `->results()` wil keep the data for the `->export()` function. You can try to reset te performance instance with `Performance::instanceReset();`

```php
Performance::point('A');
Performance::point('B');
Performance::point('C');

Performance::instanceReset(); // Reset instance

Performance::point('D');
Performance::point('E');
Performance::point('F');

Performance::results();
```

it is also possible to use the performance tool as a class (without the singleton pattern).
Example:
```php
// Create a test
$p = new PerformanceHandler();
$p->bootstrap();
$p->point('A');
$p->point('B');
$p->point('C');

// Reset (destroy + recreate)
$p = new PerformanceHandler();
$p->bootstrap();
$p->point('D');
$p->point('E');
$p->point('F');
$p->results();
```

I hope this helps
