### ISSUE TITLE
Is there a port that I can use to monitor the live statistics as my code run?

### ISSUE THREAD

**Issue by yukari1414** [bvanhoekelen/performance#19]
Example: https://localhost:8080

I'm not sure if I understand this package correctly... But does it support recording statistics on the application level or it's just capable of showing the statistics for a single PHP script?

**Comment by bvanhoekelen** [comment]
both, you decide where you put the measurement points;)

**Comment by yukari1414** [comment]
But how do I access the statistics? I'm using Laravel 5.8.

Like the [web preview](https://github.com/bvanhoekelen/performance/blob/master/assets/raw/php-performance-tool-web-support.png), where do I go to see it?

And the [command line preview](https://github.com/bvanhoekelen/performance/blob/master/assets/raw/php-performance-tool-command-line.png), what command do I run to view it? Or is the command line preview only available for single script execution?

What I hope to achieve is to add measurement points throughout my code base and gather the statistics on my production server. So it would be great if I could access the web preview. I can think of 2 ways which are:

- from a port (e.g. https://my-production-url:8080)
- a custom route. Example:
    ``` php
    Route::get('/performance-web-preview', function () {
        return view('performance.web-preview');
    });
    ```

I noticed that the data is not exactly stored anywhere like a database so I'm not sure if this is achievable. Sorry but I'm really stumped.. kinda feel like I'm missing something really obvious here..

**Comment by yukari1414** [comment]
Just in case anyone ask for my solution for closing this issue, here's what I did:
1. Have a middleware that run on every request
1. In the middleware, I extract the points' JSON
`$points = json_decode(Performance::export()->points()->toJson());`
1. Store the data to the application's database
1. Build a view that will show all the data I needed
