### ISSUE TITLE
overriding my date configuration

### ISSUE THREAD

**Issue by vesper8** [bvanhoekelen/performance#9]
I just noticed that when I have am using your package to benchmark, my timezone is overwritten

By default I have it set to Singapore 

in my config/app.php

I have

```
'timezone' => 'Asia/Singapore',
```

I was running benchmarking on aggregate queries that use the dates and I was noticing that my graphs were off and different from my production data even though I am using the same database data

I think it's because of this line:

```
    private function setDefaultTimeZone()
    {
        // Check date function
        if( ! ini_get('date.timezone'))
            date_default_timezone_set('UTC');
    }
```

In your ConfigHandler.php

Is this really necessary ? Shouldn't your benchmarking work regardless of what timezone is set?

**Comment by bvanhoekelen** [comment]
Hi Vesper8,

I checked whether it is necessary to configure the default timezone. I also think that the performance tool should not set default timezone.

The code for setting the default timezone has been removed in version v2.3.4.

Thanks for your feedback
If you have any suggestions please let know
